
GET {{host}}/tasks

###

POST {{host}}/tasks
Content-Type: application/json

{
    "name": "Necesito crear una app2",
    "description": "Utilizando Nodejs2"
}

###


GET {{host}}/tasks/count

###


GET {{host}}/tasks/P2mMuR00tUCQKCdMHD2s1

###


DELETE {{host}}/tasks/utftgaCrgO88FLHZbV9TM

###



PUT {{host}}/tasks/RR7BOO3bPUpLFh0jv6wr_
Content-Type: application/json

{
    "name": "Modifco la app12312321",
    "description": "Otro nombre123123123"
}

###